-m: dab_deformable_detr
--output_dir: logs/DABDETR/R50
--batch_size: 2
--epochs: 2
--lr_drop: 40
--transformer_activation: relu
--coco_path: ./data/coco
--train_ann_file: annotations/instances_train2017.json
--train_img_prefix: ./train2017
--val_ann_file: annotations/instances_val2017.json
--val_img_prefix: ./val2017
--test_ann_file: annotations/image_info_test-dev2017.json
--test_img_prefix: ./test2017