-m: dab_deformable_detr
--output_dir: logs/DABDETR/R50
--batch_size: 2
--epochs: 50
--lr_drop: 40
--transformer_activation: relu
--coco_path: ./data/coco
--train_ann_file: train.json
--train_img_prefix: ./train
--val_ann_file: val.json
--val_img_prefix: ./val
--test_ann_file: val.json
--test_img_prefix: ./val